@baseUrl= http://localhost:4000
@apiUrl= {{baseUrl}}/api/v1
#
GET {{baseUrl}}
###
GET {{apiUrl}}

###
POST {{apiUrl}}/auth
Content-Type: application/json
 
 {
    "username":"mai",
    "email":"mai1@gmail.com",
    "password":"test"
 }

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
 "email":"mai1@gmail.com",
 "password":"test"
}

###
 POST {{apiUrl}}/transactions
Content-Type:  application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haTFAZ21haWwuY29tIiwiaWF0IjoxNzUyNzU3NDI2LCJleHAiOjE3NTI4NDM4MjZ9.z05v2-2L1z6YkmRkLAo6ptZoecehRUkQHTelnMEwcUw 
{
   "type":"expense",
   "description":"mai expense cdasd",
   "date":"12-10-2022",
   "amount":240001
}
###
GET {{apiUrl}}/transactions
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haUBnbWFpbC5jb20iLCJpYXQiOjE3NTI2NzI5OTUsImV4cCI6MTc1Mjc1OTM5NX0.wJbRg16qSW0U3sxsSCY3u2xIsm1cdFOG9adYgRpBrRM


###
DELETE {{apiUrl}}/delete/6877ab241fa0bac89463450f
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haUBnbWFpbC5jb20iLCJpYXQiOjE3NTI2NzI5OTUsImV4cCI6MTc1Mjc1OTM5NX0.wJbRg16qSW0U3sxsSCY3u2xIsm1cdFOG9adYgRpBrRM
